application:
  id: harman-vaccination
  environment: local
  logType: Application
  name: Harman vaccination drive
  platformName: harmanvac
  serviceName: harman-vaccination-services
  version: 2.0
maven:
  basedir: '@project.basedir@'
server:
  port: 17002

spring:
  data:
    rest:
      basePath: /harman/vaccination/v1
      default-page-size:  50
  h2:
    console:
      enabled: true
      path: /h2

  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:h2:mem:harmanvac
    username: vaccine
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        dialect: org.hibernate.dialect.H2Dialect
      show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 500MB
applicationmode: dev
threadPool:
  maxPoolSize: 5
  corePoolSize: 5
  queueCapacity: 50
  awaitTerminationSec: 120

